### ISSUE TITLE
size mismatch for action_out.weight: copying a param with shape torch.Size([4, 256]) from checkpoint, the shape in current model is torch.Size([6, 256]).

### ISSUE THREAD

**Issue by Lygggggg** [LM095/DRL-for-Pick-and-Place-Task-subtasks#1]
Hello, when I run to the Train the High-Level Synthesizer (HLS) step, I encountered an error. The error shows that the dimensions of the imported model are inconsistent with the required ones. I suspect that it is the first step Train the Low-level There is a problem with the model parameters generated by Subtask Expert (LSE), but I don’t know how to modify it. Can you please provide some help?

The error displayed on the terminal is as shown below:

Cuda: True
Loading A3C parametets ...
No of available cores : 16
<Synchronized wrapper for c_int(0)>
Cuda: True
Cuda: True
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lni/PycharmProjects/ReinforcementLearningPick/Multi-Subtask-DRL-for-Pick-and-Place-Task/HLS/dense_rewardDDPG_HER.py", line 64, in train
    actor_network_approach.load_state_dict(model_approach)
  File "/home/lni/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for actor:
	size mismatch for action_out.weight: copying a param with shape torch.Size([4, 256]) from checkpoint, the shape in current model is torch.Size([6, 256]).
	size mismatch for action_out.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([6]).
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lni/PycharmProjects/ReinforcementLearningPick/Multi-Subtask-DRL-for-Pick-and-Place-Task/HLS/dense_rewardDDPG_HER.py", line 381, in test
    actor_network_approach.load_state_dict(model_approach)
  File "/home/lni/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for actor:
	size mismatch for action_out.weight: copying a param with shape torch.Size([4, 256]) from checkpoint, the shape in current model is torch.Size([6, 256]).
	size mismatch for action_out.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([6]).

**Comment by LM095** [comment]
Hi Lygggg,
thanks for the interestest in my work! I tried the section cloning the repo and for me worked. As you notice probably there is an error caused by a wrong import of the weights, I mean it cannot find the weights. Check if in the folder "weights" you have these files: actor_params.pt,  approach.pt, manipulate.pt and retract.pt (I attached a picture
![weights](https://user-images.githubusercontent.com/50518316/119217689-18686b80-badc-11eb-8aa7-db6ebcde7d53.png)
).
If you have everything in the folder, you can run the main without any problems. Hope I helped you.

**Comment by lmarza** [comment]
Hi Lygggg,
thanks for the interestest in my work! I tried the section cloning the repo and for me worked. The problem is caused by the fact that the basic gym version 0.10.8 used has been modified to use only 4 actions, now I have imported it into the repo so you can directly use that and there should be no problem. Thank you so much for the comment.

**Comment by Lygggggg** [comment]
Thanks for you reply,i have solved the problem.

Luca Marzari ***@***.***> 于2021年5月22日周六 下午3:29写道：
