### ISSUE TITLE
Hierarchical Task

### ISSUE THREAD

**Issue by quyouyuan** [LM095/DRL-for-Pick-and-Place-Task-subtasks#2]
Hello! I'm very interested in hierarchical thinking,and it's a very important thought in RL. What does "action [3] = -0.01" mean? I want to divide "fetchpush-v1" and "fetchslide-v1" into "approach" and "push". I can directly use "fetchpickandplace ddpg + her / rl_modules / ddpg_agent_manual. Py" for the skills of "push". Can you give some code guidance? Thank you very much for replying in your busy schedule!

**Comment by lmarza** [comment]
Hi! Thanks for your interest in this work. The action[3] = -0.01 is inherent to the gripper closure that is not trained but manually set because this work aims to compare BC and DRL in learning the basic behavior such as approach, manipulate, and retract. As you can see, action[3] value changes following the subtask we are training. In the "approach" subtask, for example, we set the gripper closure to 0.05, which is a positive value and implies that the gripper is open (in general, if the value is positive, you are opening the gripper, and if it is negative you are closing the gripper. The value implies how fast you open/close the gripper. You can make some tests also using hand-engineered solutions provided by OpenAI).

For the second question, "fetchpush-v1" and "fetchslide-v1" tasks are complex to divide into approach and push/slide. I did some tests one year ago to try to reuse the "approach" subtask of "fetchPickAndPlace" for "fetchpush-v1", and the results were interesting but not so significant, maybe because I used only a fine-tuning approach. I'm dealing with other research topics now and wouldn't know how to help you more, sorry. I hope this answer was helpful to you. Greetings

**Comment by quyouyuan** [comment]
Thank you very much for your reply, which is very important to me. Could you provide the code  of “fetchpush-v1" and "fetchslide-v1" hierarchical subtasks? If you can provide, please send my email: quyouyuanyingying@163.com.Thank you very much for your help!
